name: Kalkuliator
description: Paprastas kalkuliatorius, su kurio pagalba galėsite atlikti paprastas matematikos operacijas.
publish_to: 'none'

version: 1.1.1+1


environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.3.0
  math_expressions: ^2.0.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.18
  audioplayers: 6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/hl2.mp3
    - assets/sounds/metal.mp3
    - assets/sounds/click.mp3
    - assets/icon.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/appicon.png"
